<!DOCTYPE html>
<html>
<head>
    <title>Sales Report - {{ $filter_label }}</title>
    <style>
        body { 
            font-family: 'Helvetica', 'Arial', sans-serif; 
            font-size: 11px; 
            color: #333;
        }
        .header { 
            text-align: center; 
            margin-bottom: 30px; 
            border-bottom: 2px solid #444;
            padding-bottom: 10px;
        }
        .header h2 { 
            text-transform: uppercase; 
            margin-bottom: 5px; 
            letter-spacing: 2px;
        }
        .header p { 
            margin: 0; 
            color: #777; 
            font-style: italic;
        }
        table { 
            width: 100%; 
            border-collapse: collapse; 
            margin-bottom: 20px; 
        }
        th, td { 
            border: 1px solid #eee; 
            padding: 10px 8px; 
            text-align: left; 
        }
        th { 
            background-color: #111318; 
            color: #ffffff;
            font-weight: bold; 
            text-transform: uppercase; 
            font-size: 9px;
            letter-spacing: 1px;
        }
        tr:nth-child(even) {
            background-color: #fafafa;
        }
        .status-badge {
            font-weight: bold;
            text-transform: uppercase;
            font-size: 8px;
        }
        .total-section { 
            margin-top: 30px;
            text-align: right; 
            border-top: 2px solid #111318;
            padding-top: 10px;
        }
        .total-label {
            font-size: 10px;
            text-transform: uppercase;
            color: #888;
        }
        .total-amount {
            font-size: 16px;
            font-weight: bold;
            color: #111318;
        }
    </style>
</head>
<body>
    <div class="header">
        <h2>LUXE PREMIUM SALES REPORT</h2>
        <p>Period Engagement: {{ $filter_label }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th width="12%">Order ID</th>
                <th width="15%">Date</th>
                <th width="20%">Customer</th>
                <th width="25%">Product Narrative</th> {{-- Kolom Nama Produk Baru --}}
                <th width="13%">Status</th>
                <th width="15%">Investment</th>
            </tr>
        </thead>
        <tbody>
            @foreach($orders as $order)
            <tr>
                <td style="font-weight: bold;">#ORD-{{ $order->id }}</td>
                <td>{{ date('d M Y', strtotime($order->created_at)) }}</td>
                <td>{{ $order->first_name }} {{ $order->last_name }}</td>
                <td style="text-transform: uppercase; font-size: 9px;">{{ $order->product_name }}</td> {{-- Data Produk --}}
                <td class="status-badge">{{ $order->status }}</td>
                <td style="text-align: right;">IDR {{ number_format($order->total_price, 0, ',', '.') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="total-section">
        <span class="total-label">Grand Total Revenue</span><br>
        <span class="total-amount">IDR {{ number_format($total, 0, ',', '.') }}</span>
    </div>

    <div style="margin-top: 50px; text-align: center; color: #ccc; font-size: 9px; text-transform: uppercase; letter-spacing: 3px;">
        Generated by LUXE Management System • {{ date('d/m/Y H:i') }}
    </div>
</body>
</html>